platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AMIaide' do
  # Pods for AMIaide
  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'



  pod 'agora-react-native-rtm', :path => '../node_modules/agora-react-native-rtm'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  target 'AMIaideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

target 'AMIaide-tvOS' do
  # Pods for AMIaide-tvOS

  target 'AMIaide-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
