/*
Mocks goes here
If this file become too big, make a mock folder and split your mocks in files
*/

export const fetchPatientMock = () => {
  const error = null;
  const response = {
      "data": [
          {
              "id": 5,
              "diet_id": 15,
              "user_id": 17,
              "name": "Blervaque",
              "firstname": "Alexis",
              "sex": "M.",
              "birthday": "1996-10-05",
              "postalCode": "92800",
              "city": "64 Rue Sadi Carnot",
              "portable": "0619410946",
              "phone": "0619410943",
              "email": "alexis.blervaque@telecos",
              "enceinte": "Non",
              "contactFrom": null,
              "comments": null,
              "situation": "Célibataire",
              "profiles": [
                  1
              ],
              "advices": [
                  1,
                  5
              ],
              "created_at": "2018-05-11 16:14:35",
              "updated_at": "2019-07-04 12:11:31",
              "imagePath": "mxmi1E0dQ5rSGyIU4x7YsSIX4LTqVqprgWCiH6VK.jpeg",
              "deviceToken": "ejzukL5S_48:APA91bHzXp5pBpbLC4nb-F_GHTNupnJRswcbEqaXXGmfsmBcjhcOCjuHEEYsPG28m6Y_F0IHr9bD6oTyQ1xVvrAQdGbrBkc4YA0zqkLTf1pdM3yRPLMtjG2V_qHNTJ2RxVHJEqkNMdWn",
              "username": "b.alexis",
              "last_consultation": "12/06/2019"
          },
          {
              "id": 6,
              "diet_id": 15,
              "user_id": 23,
              "name": "ORTUNO",
              "firstname": "Olivier",
              "sex": "M.",
              "birthday": "1979-04-08",
              "postalCode": "92800",
              "city": "64 rue sadi carnot",
              "portable": "0623158073",
              "phone": null,
              "email": "olivierortuno@hotmail.com",
              "enceinte": null,
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": null,
              "situation": "Marié(e)",
              "profiles": null,
              "advices": [
                  1
              ],
              "created_at": "2018-05-17 09:25:59",
              "updated_at": "2019-02-11 11:00:14",
              "imagePath": null,
              "deviceToken": "dkIQvLlUSEc:APA91bEREIu0Rij-x3TrL83jGQu7Vey1cSUroJQII1UVP2lHakgtqqlk-9PuG7zMsN0DVUh2Z2TOckDEHES-MmxTlTKIOcZ8K_DF-QH-aM1K9zcONkkb_So4u0lH-cN7pONHZ2cV0ceoKqNvf4TX-mkSCisCidKciQ",
              "username": "oortuno"
          },
          {
              "id": 7,
              "diet_id": 15,
              "user_id": null,
              "name": "Ortuno",
              "firstname": "olivier",
              "sex": "M.",
              "birthday": "1979-04-08",
              "postalCode": "92800",
              "city": "64 rue sadi carnot",
              "portable": "0659921600",
              "phone": null,
              "email": "olivierortuno@hotmail.com",
              "enceinte": "Non",
              "contactFrom": null,
              "comments": null,
              "situation": "Marié(e)",
              "profiles": null,
              "advices": null,
              "created_at": "2018-05-17 09:34:31",
              "updated_at": "2018-05-17 09:34:31",
              "imagePath": null,
              "deviceToken": null
          },
          {
              "id": 9,
              "diet_id": 15,
              "user_id": 24,
              "name": "Ortuno",
              "firstname": "Lohen",
              "sex": "Mme.",
              "birthday": "1982-05-08",
              "postalCode": "92800",
              "city": "64 rue sadi carnot puteaux",
              "portable": "0623158073",
              "phone": null,
              "email": "l.dijoux@yahoo.fr",
              "enceinte": "Non",
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": null,
              "situation": "Marié(e)",
              "profiles": null,
              "advices": null,
              "created_at": "2018-07-18 16:11:57",
              "updated_at": "2019-02-11 15:56:44",
              "imagePath": null,
              "deviceToken": null,
              "username": "lohenort",
              "last_consultation": "20/06/2019"
          },
          {
              "id": 10,
              "diet_id": 15,
              "user_id": null,
              "name": "ORTUNO",
              "firstname": "Joan",
              "sex": "M.",
              "birthday": null,
              "postalCode": null,
              "city": null,
              "portable": null,
              "phone": null,
              "email": null,
              "enceinte": null,
              "contactFrom": null,
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2018-11-24 18:13:53",
              "updated_at": "2019-02-11 15:55:32",
              "imagePath": null,
              "deviceToken": null
          },
          {
              "id": 11,
              "diet_id": 15,
              "user_id": 26,
              "name": "Oliv",
              "firstname": "ORTUNO",
              "sex": "M.",
              "birthday": "1979-04-08",
              "postalCode": null,
              "city": null,
              "portable": "0659921600",
              "phone": null,
              "email": null,
              "enceinte": null,
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2019-02-07 12:37:38",
              "updated_at": "2019-02-07 12:39:20",
              "imagePath": null,
              "deviceToken": null,
              "username": "oliv",
              "last_consultation": "07/02/2019"
          },
          {
              "id": 12,
              "diet_id": 15,
              "user_id": 27,
              "name": "rugery",
              "firstname": "pierrick",
              "sex": "M.",
              "birthday": null,
              "postalCode": "91000",
              "city": "14 rue charles fourier",
              "portable": "0000000000",
              "phone": null,
              "email": "pierrick.rugery@sptint-je.com",
              "enceinte": "Non",
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": "<p>Aucun commentaire particulier</p>",
              "situation": "Marié(e)",
              "profiles": null,
              "advices": null,
              "created_at": "2019-02-09 09:58:28",
              "updated_at": "2019-02-09 09:59:11",
              "imagePath": null,
              "deviceToken": null,
              "username": "p.rugery"
          },
          {
              "id": 13,
              "diet_id": 15,
              "user_id": null,
              "name": "CLEMENT",
              "firstname": "Odette",
              "sex": "Mme.",
              "birthday": "1967-06-12",
              "postalCode": "93000",
              "city": null,
              "portable": null,
              "phone": null,
              "email": null,
              "enceinte": null,
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": null,
              "situation": null,
              "profiles": [
                  1
              ],
              "advices": null,
              "created_at": "2019-02-12 10:37:30",
              "updated_at": "2019-02-12 13:25:12",
              "imagePath": null,
              "deviceToken": null,
              "last_consultation": "12/02/2019"
          },
          {
              "id": 14,
              "diet_id": 15,
              "user_id": null,
              "name": "rugery",
              "firstname": "test",
              "sex": "M.",
              "birthday": null,
              "postalCode": "33000",
              "city": "14 rue de marseille",
              "portable": "0000000000",
              "phone": "0000000000",
              "email": "pierrick.rugery@sprint-je.com",
              "enceinte": null,
              "contactFrom": [
                  "Google"
              ],
              "comments": "<p>RAS</p>",
              "situation": "Marié(e)",
              "profiles": null,
              "advices": null,
              "created_at": "2019-02-19 13:35:07",
              "updated_at": "2019-02-19 13:35:07",
              "imagePath": null,
              "deviceToken": null,
              "last_consultation": "19/02/2019"
          },
          {
              "id": 16,
              "diet_id": 15,
              "user_id": null,
              "name": "Eric",
              "firstname": "Jean",
              "sex": "M.",
              "birthday": "1977-05-21",
              "postalCode": null,
              "city": null,
              "portable": null,
              "phone": null,
              "email": "Je",
              "enceinte": null,
              "contactFrom": [
                  "Doctolib"
              ],
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2019-05-23 08:35:56",
              "updated_at": "2019-05-23 08:35:56",
              "imagePath": null,
              "deviceToken": null
          },
          {
              "id": 17,
              "diet_id": 15,
              "user_id": null,
              "name": "VRIGNEAU",
              "firstname": "1",
              "sex": "Mme.",
              "birthday": "1988-01-05",
              "postalCode": "53000",
              "city": "6 rue Léonard de Vinci",
              "portable": "0253353650",
              "phone": null,
              "email": "favre.thomas91@gmail.com",
              "enceinte": null,
              "contactFrom": [
                  "Google"
              ],
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2019-05-31 13:03:33",
              "updated_at": "2019-05-31 13:03:33",
              "imagePath": null,
              "deviceToken": null
          },
          {
              "id": 18,
              "diet_id": 15,
              "user_id": 47,
              "name": "favre",
              "firstname": "thomas",
              "sex": "M.",
              "birthday": "1997-01-29",
              "postalCode": "49400",
              "city": "2 rue gambetta",
              "portable": "0681431665",
              "phone": null,
              "email": "favre.thomas91@gmail.com",
              "enceinte": "Non",
              "contactFrom": [
                  "Bouche à oreille"
              ],
              "comments": "<p>qzsedrftgyhuj</p>",
              "situation": "En couple",
              "profiles": null,
              "advices": null,
              "created_at": "2019-05-31 13:05:22",
              "updated_at": "2019-05-31 13:05:39",
              "imagePath": null,
              "deviceToken": null,
              "username": "azerty"
          },
          {
              "id": 19,
              "diet_id": 15,
              "user_id": null,
              "name": "jaques",
              "firstname": "france",
              "sex": null,
              "birthday": null,
              "postalCode": null,
              "city": null,
              "portable": null,
              "phone": null,
              "email": null,
              "enceinte": null,
              "contactFrom": null,
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2019-06-06 09:41:53",
              "updated_at": "2019-06-06 09:41:53",
              "imagePath": null,
              "deviceToken": null
          },
          {
              "id": 20,
              "diet_id": 15,
              "user_id": 49,
              "name": "BROUET",
              "firstname": "Louise",
              "sex": "Mme.",
              "birthday": "2000-06-17",
              "postalCode": "92800",
              "city": null,
              "portable": "0623158073",
              "phone": null,
              "email": "l.dijoux@yahoo.fr",
              "enceinte": "Non",
              "contactFrom": null,
              "comments": null,
              "situation": "Célibataire",
              "profiles": [
                  2
              ],
              "advices": null,
              "created_at": "2019-06-17 07:29:49",
              "updated_at": "2019-06-17 07:32:41",
              "imagePath": null,
              "deviceToken": null,
              "username": "brouet",
              "last_consultation": "17/06/2019"
          },
          {
              "id": 21,
              "diet_id": 15,
              "user_id": null,
              "name": "gtyu",
              "firstname": "fre",
              "sex": null,
              "birthday": null,
              "postalCode": null,
              "city": null,
              "portable": null,
              "phone": null,
              "email": null,
              "enceinte": null,
              "contactFrom": null,
              "comments": null,
              "situation": null,
              "profiles": null,
              "advices": null,
              "created_at": "2019-06-28 10:43:24",
              "updated_at": "2019-06-28 10:43:24",
              "imagePath": null,
              "deviceToken": null
          }
      ]
  }
  return new Promise(resolve => {
    setTimeout(() => {
      resolve([error, response]);
    }, 3000);
  })
};
